### ISSUE TITLE
Cannot authenticate client against LXD

### ISSUE THREAD

**Issue by fabfurnari** [lxc/pylxd#140] opened 2016-06-16 22:28 UTC
Hello, not sure if bug or intended:

Following[ this procedure](https://pylxd.readthedocs.io/en/latest/authentication.html) I've tried to setup a simple client:

`from pylxd import Client`
`c = Client(endpoint='http://192.168.33.10:8443', cert=('client.crt', 'client.key'), verify=False)`

Theorically it should create a `Client` instance that later I can authenticate with the `authenticate()` method and the trust password (already set in LXD) but every time I get the exception:

```
ClientAuthenticationFailed: LXD client certificates are not trusted.
```

Seems that in pylxd==2.0.2 (currently the latest available in PyPI) the client raise an exception every time is not authenticated, so it's impossible to register new certificates.

I noted also that in the current code available on GitHub this should be fixed.

**Comment by fabfurnari** [comment] 2016-06-16 22:30
Sorry, I've just noted that this is fixed with the latest PR, however the current version in PyPI is broken.

**Comment by rockstar** [comment] 2016-06-20 14:33
Hm. I just tried to reproduce this is 2.0.2, and I can't.  You say this was fixed in a recent PR? Do you know which one? There have only been two PRs since the release of 2.0.2.

**Comment by fabfurnari** [comment] 2016-06-20 14:54
Issue has been fixed here: https://github.com/lxc/pylxd/commit/0bc96973f5c0a73563d62d547366a34ca6883f0b#diff-736e104e227dd4935d4f1d791908d82eL187

**Comment by rockstar** [comment] 2016-06-23 15:27
Oh, my apologies. I thought I had gotten this in for the 2.0.2 release, but that patch was merged shortly after. It'll be in 2.0.3

**Comment by rockstar** [comment] 2016-06-28 01:21
I'd been leaving this issue open until 2.0.3 was released, but I've been closing other issues when they are in master. Closing this one to follow that. 2.0.3 will be released this week.

**Closed by rockstar** 2016-06-28 01:21 UTC
