### ISSUE TITLE
Creating a new container in Ubuntu bionic with lxd 3 (via snap) gives No storage pool found. 

### ISSUE THREAD

**Issue by shuhaowu** [lxc/pylxd#306] opened 2018-05-24 18:58 UTC
Not sure why this is the case. The command line lxc tooling works but pylxd does not. See trace below.

I've used this setup in artful, xenial, and debian stretch and it all seems to work, but on this machine it somehow does not.

```
ubuntu@test-01:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
ubuntu@test-01:~$ lxc storage list
+---------+-------------+--------+------------------------------------+---------+
|  NAME   | DESCRIPTION | DRIVER |               SOURCE               | USED BY |
+---------+-------------+--------+------------------------------------+---------+
| default |             | dir    | /var/lib/lxd/storage-pools/default | 1       |
+---------+-------------+--------+------------------------------------+---------+
ubuntu@test-01:~$ lxc launch ubuntu:16.04
Creating the container
Container name is: talented-grub
Starting talented-grub
ubuntu@test-01:~$ lxc list
+---------------+---------+------+----------------------------------------------+------------+-----------+
|     NAME      |  STATE  | IPV4 |                     IPV6                     |    TYPE    | SNAPSHOTS |
+---------------+---------+------+----------------------------------------------+------------+-----------+
| talented-grub | RUNNING |      | fd42:ca9:35a7:8fe6:216:3eff:fe1f:a2cd (eth0) | PERSISTENT | 0         |
+---------------+---------+------+----------------------------------------------+------------+-----------+
ubuntu@test-01:~$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylxd
>>> pylxd.__version__
'2.2.6'
>>> c = pylxd.Client()
>>> c.containers.create({'name': 'test1', 'source': {'alias': 'ubuntu/xenial', 'mode': 'pull', 'protocol': 'simplestreams', 'server': 'https://images.linuxcontainers.org', 'type': 'image'}})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pylxd/models/container.py", line 181, in create
    response = client.api.containers.post(json=config)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pylxd/client.py", line 134, in post
    self._assert_response(response, allowed_status_codes=(200, 201, 202))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pylxd/client.py", line 91, in _assert_response
    raise exceptions.LXDAPIException(response)
pylxd.exceptions.LXDAPIException: No storage pool found. Please create a new storage pool.
```

**Comment by ajkavanagh** [comment] 2018-05-29 11:50
Hmm, I've tried to replicate it using bionic and python-pylxd package and can't reproduce it.  e.g.

```
$ lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: no
Do you want to configure a new storage pool? (yes/no) [default=yes]: yes
Name of the new storage pool [default=default]: 
Name of the storage backend to use (btrfs, dir, lvm) [default=btrfs]: dir
Would you like to connect to a MAAS server? (yes/no) [default=no]: no
Would you like to create a new network bridge? (yes/no) [default=yes]: yes
What should the new bridge be called? [default=lxdbr0]: 
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: none
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 
ubuntu@ajkavanagh-bionic-test:~$ lxc storage list
+---------+-------------+--------+------------------------------------+---------+
|  NAME   | DESCRIPTION | DRIVER |               SOURCE               | USED BY |
+---------+-------------+--------+------------------------------------+---------+
| default |             | dir    | /var/lib/lxd/storage-pools/default | 1       |
+---------+-------------+--------+------------------------------------+---------+

$ lxc launch ubuntu:16.04 xenial-test
Creating xenial-test
Starting xenial-test

$ $ ipython3
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pylxd

In [2]: pylxd.__version__
Out[2]: '2.2.6'

In [3]: c = pylxd.Client()

In [4]: c.containers.create({'name': 'test1', 'source': {'alias': 'ubuntu/xenial', 'mode': 'pull', 'protocol': 'simplestreams'
   ...: , 'server': 'https://images.linuxcontainers.org', 'type': 'image'}})
Out[4]: <pylxd.models.container.Container at 0x7f3990097d90>

In [5]: c.containers.all()
Out[5]: 
[<pylxd.models.container.Container at 0x7f3990097e58>,
 <pylxd.models.container.Container at 0x7f3990097f20>]
```

This is on a bionic image: ubuntu-released/ubuntu-bionic-18.04-amd64-server-20180522-disk1.img (7938fb5c-3fc1-47c5-9e17-1ce1dcf813f2)

Have you got any more info?

**Comment by shuhaowu** [comment] 2018-05-29 15:50
I tested it locally and it seemed to worked as well. The issue might lie somewhere in the openstack virtual machine setup, but I'm not sure as I don't quite know how to debug any further.

**Comment by ajkavanagh** [comment] 2018-05-30 08:10
@shuhaowu can you provide any more details.  e.g. it sounds like this is on a VM in OpenStack.  Is that a libvirt VM or lxd VM (i.e. lxd in lxd).  Or something else.  Would be good to try to nail down what might be different.  I suspect it's a bug/issue in lxc/lxd rather than pylxd.

**Comment by ajkavanagh** [comment] 2018-08-30 14:36
I recently fixed, in nova-lxd, an issue around storage pools, bionic and OpenStack queens: https://bugs.launchpad.net/nova-lxd/+bug/1782329

This is now in SRU (Stable Release Update): https://bugs.launchpad.net/ubuntu/+source/nova-lxd/+bug/1789427.

I'll close this as soon as that is out.

**Comment by cjohnston1158** [comment] 2019-01-12 00:45
I was running into the same error running in an 18.04 VM. I was able to fix is using the solution [here](https://discuss.linuxcontainers.org/t/failed-to-create-container-no-such-pool/319/14)

**Comment by cjohnston1158** [comment] 2019-01-24 19:17
New install of Ubuntu 18.04.1. Installed lxd snap, lxd init, ran into problems. Followed the posted solution and the error went away.

Package: python3-pylxd
Version: 2.2.6-0ubuntu1.1

lxd snap is 3.9

**Comment by ajkavanagh** [comment] 2019-01-24 20:06
This isn't a pylxd issue *per se*, but rather an LXD install issue.  The issue is that on a new install of Ubuntu 18.04 the apt packaged version of LXD will be installed (3.0.3 or other minor point release).

Doing the snap install *adds* a snap version of LXD; currently 3.9.

What you *should* do immediately after running `sudo snap install lxd` is to do `sudo lxd.migrate` which will (if you follow the default defaults) leave you with a *single* LXD installation.  pylxd will then find the snap version via a unix socket when running on the same machine.

If you *don't* run `lxd.migrate` then there will be two copies of LXD running on the machine which isn't a supported configuration by either pylxd or LXD.  Also the snap version won't be configured.  If the packaged version *is* configured and you run `lxd.migrate` then the storage pools, config, and containers will be migrated to the snap version.  However, you will *also* need to move the lxc *client's* configuration; a note is printed at the end of the `lxd.migrate` command.

My advice is if you don't need the newer features of 3.9 on Ubuntu 18.04, then stick with the package version for the moment, or if you do need the newer features (clustering, etc.) then update your tooling to ensure (on new installations of 18.04) that you do do the `lxd.migrate` dance to migrate to the snap version *and* delete the package version.

`pylxd` will work with either the packaged version or the snap version but is not designed to work with both, and as it's an unsupported LXD configuration, isn't going to grow support for that configuration.  Obviously, if it's a remote server then it's won't be an issue.

**Comment by ajkavanagh** [comment] 2019-05-01 10:18
This was fix-released in bionic/queens, so I'm now closing the bug:

https://bugs.launchpad.net/ubuntu/+source/nova-lxd/+bug/1789427

**Closed by ajkavanagh** 2019-05-01 10:18 UTC
Labels: needs information
